<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<div class="product-addto-links" data-role="add-to-links">
    <?= $block->getChildHtml() ?>
    <a href="#" data-role="add-to-links" class="action print-page">
		<span class="material-icons">print</span>
		<span><?= $block->escapeHtml(__('Print Page')) ?></span>
	</a>
</div>
