<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>
<div class="navigation-toggle d-none d-md-block" id="navigation-toggle">
	<span><?= __('All Products');?></span>
	<?= $block->getChildHtml('highlights') ?>
</div>
<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @noEscape */ $_menuHtml?>
    </ul>
</nav>
<script>
    require([
        'jquery'
    ], function ($) {
		$(document).ready(function() {
	    	$('#navigation-toggle > span').click(function() {
	    		if($(this).parent().hasClass('open')) {
	    			$(this).parent().removeClass('open');
	    			$(this).parent().next('nav.navigation').hide();
	    		} else {
	    			$(this).parent().addClass('open');
	    			$(this).parent().next('nav.navigation').show();
	    		}
	    	});
		});
    });
</script>