<ul class="ksps d-none d-md-block">
	<li><a href="/quickorder"><em class="material-icons">playlist_play</em> Quick Order</a></li>
	<li><a href="/contact"><em class="material-icons">chrome_reader_mode</em> Free Catalog</a></li>
	<li><a href="/customer-service"><em class="material-icons">person</em> Customer Service</a></li>
	<li><a href="/store-planning"><em class="material-icons">store</em> Store Planning</a></li>
	<li><a href="/location-directions"><em class="material-icons">location_on</em> Locations &amp; Directions</a></li>
</ul>